services:
  # Backend API Service
  - type: web
    name: company-scraper-backend
    env: docker
    dockerfilePath: ./backend_api/Dockerfile
    dockerContext: ./
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_O0peSW3nPiDj@ep-steep-cloud-a8peyzo3-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DB_HOST
        value: ep-steep-cloud-a8peyzo3-pooler.eastus2.azure.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_O0peSW3nPiDj
      - key: DB_DRIVER
        value: postgresql
      - key: DB_SSL_MODE
        value: require
    startCommand: uvicorn backend_api.main:app --host 0.0.0.0 --port 8000 --log-level warning

  # Frontend Service
  - type: web
    name: company-scraper-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://company-scraper-backend-90mt.onrender.com/api